-   id: mypy
    name: mypy
    description: ''
    entry: mypy
    language: python
    'types_or': [python, pyi]
    args: ["--ignore-missing-imports", "--scripts-are-modules"]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
